### ISSUE TITLE
Add sample text for Maori

### ISSUE THREAD

**Issue by RosaWagner** [googlefonts/lang#55]
After a complain from a user https://twitter.com/fauxparse/status/1602944061023088643 saying the macron accent in Maori sample text were removed, I wanted to check out the textproto, but couldn't find any. So I guess we need to add one to fix the issue?

**Comment by fauxparse** [comment]
Thanks! For reference, I'm referring to the sample text that appeared in the screenshot attached to the above tweet, which may have been auto-translated? Regardless, I'm reasonably sure the text should read "Nō te mea ki te kore te tangata ae ākina kia tae ki te tino [or possibly tinō?] hemānawatanga", but it would of course be good to consult an authority on it :)

Macron support is far from universal, but a prime consideration for people choosing fonts for use in Aotearoa/New Zealand, since Māori uses macrons extensively — and they can change the meaning drastically! "Wētā" = a native insect, but weta = "shit". Being able to view this when a font is previewed would lead to better outcomes for Kiwi developers.

Thanks for looking into this!

**Comment by simoncozens** [comment]
The official [UDHR translation](https://www.ohchr.org/en/human-rights/universal-declaration/translations/maori) does not contain any words with macrons - which is a bit suspicious. I agree that if it is correct, it's not a great sample in terms of showing off language support. But if it is correct, it's a good text to use.

However I don't think this is a killer for choosing fonts. On Google Fonts, selecting "Maori" in the language dropdown will only show fonts which fully support all characters in the Maori repertoire.

<img width="565" alt="Screenshot 2024-09-12 at 07 52 29" src="https://github.com/user-attachments/assets/3ac6888e-b740-4b2d-a427-1d2413184c17">

**Comment by moyogo** [comment]
Well, it’s not correct and the issue shouldn’t be closed.

The OHCHR.org’s [PDF](https://www.ohchr.org/sites/default/files/UDHR/Documents/UDHR_Translations/mbf.pdf) of the Maori UDHR has the macrons while the [webpage](https://www.ohchr.org/en/human-rights/universal-declaration/translations/maori) does not. Both have a different Maori translation. My guess is the webpage has an old translation, without macron either because it predates the adoption of the macron in the 1987 spelling or because macrons were lost in digitization.
Either way, the version with macron should be used.
